version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing AWS CLI..."
      - if command -v yum > /dev/null; then yum update -y && yum install -y aws-cli; fi
      - if command -v apt-get > /dev/null; then apt-get update && apt-get install -y awscli; fi
      - if command -v apk > /dev/null; then apk add --no-cache aws-cli; fi
      - aws --version  # Verify installation

  pre_build:
    commands:
      - echo "Checking CloudFormation templates..."
      - ls -l Bastion-Host/Bastion-Test/  # Debugging step to ensure files exist

  build:
    commands:
      - echo "Deploying VPC..."
      - aws cloudformation deploy --template-file "Bastion-Host/Bastion-Test/VPC-Temp.yml" --stack-name VPCStack --capabilities CAPABILITY_NAMED_IAM --debug 2>&1 | tee cloudformation-debug.log


  post_build:
    commands:
      - echo "Checking Build Status..."
      - if [ $? -eq 0 ]; then echo "✅ Deployment completed successfully!"; else echo "❌ Deployment failed! Check logs for details."; exit 1; fi

artifacts:
  files:
    - '**/*'
