version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws --version  # Verify AWS CLI installation
      - echo "Installing CloudFormation Linter"
      - pip install cfn-lint  # Install CloudFormation template linter

  pre_build:
    commands:
      - echo "Checking CloudFormation templates..."
      - ls -l Bastion-Host/Bastion-Test/  # List files for debugging
      - echo "Checking if template files exist..."
      - |
        test -f Bastion-Host/Bastion-Test/VPC-Temp.yml
        echo $?
        ls -l Bastion-Host/Bastion-Test/
        if [ $? -ne 0 ]; then
          echo "Error: VPC-Temp.yml not found"
          exit 1
        fi
  

  build:
    commands:
      - echo "Deploying VPC..."
      - aws cloudformation deploy --template-file "Bastion-Host/Bastion-Test/VPC-Temp.yml" --stack-name VPCStack --capabilities CAPABILITY_NAMED_IAM



  post_build:
    commands:
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'
