version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing AWS CLI..."
      - if command -v yum > /dev/null; then yum update -y && yum install -y aws-cli; fi
      - if command -v apt-get > /dev/null; then apt-get update && apt-get install -y awscli; fi
      - if command -v apk > /dev/null; then apk add --no-cache aws-cli; fi
      - aws --version  # Verify installation

  pre_build:
    commands:
      - echo "Listing available CloudFormation templates..."
      - ls -l Bastion-Host/Bastion-Test/ || (echo "Error: Template directory not found. Exiting." && exit 1)

  build:
    commands:
      - echo "Validating and Deploying VPC..."
      - |
        echo "Validating VPC Template..."
        if ! aws cloudformation validate-template --template-body file://Bastion-Host/Bastion-Test/VPC-Temp.yml; then
          echo "Error: VPC template validation failed. Exiting."
          aws cloudformation validate-template --template-body file://Bastion-Host/Bastion-Test/VPC-Temp.yml --debug
          exit 1
        fi

        echo "Deploying VPC..."
        if ! aws cloudformation deploy \
          --template-file Bastion-Host/Bastion-Test/VPC-Temp.yml \
          --stack-name VPCStack \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1; then
          echo "Error: VPC deployment failed. Exiting."
          aws cloudformation describe-stack-events --stack-name VPCStack --region us-east-1
          exit 1
        fi
        echo "VPC deployment complete."

      - echo "Validating and Deploying Tunnel Instance..."
      - |
        echo "Validating Tunnel Instance Template..."
        if ! aws cloudformation validate-template --template-body file://Bastion-Host/Bastion-Test/Tunnel-Instance.yml; then
          echo "Error: Tunnel Instance template validation failed. Exiting."
          aws cloudformation validate-template --template-body file://Bastion-Host/Bastion-Test/Tunnel-Instance.yml --debug
          exit 1
        fi

        echo "Deploying Tunnel Instance..."
        if ! aws cloudformation deploy \
          --template-file Bastion-Host/Bastion-Test/Tunnel-Instance.yml \
          --stack-name TunnelStack \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1; then
          echo "Error: Tunnel Instance deployment failed. Exiting."
          aws cloudformation describe-stack-events --stack-name TunnelStack --region us-east-1
          exit 1
        fi
        echo "Tunnel Instance deployment complete."

      - echo "Validating and Deploying Private Instance..."
      - |
        echo "Validating Private Instance Template..."
        if ! aws cloudformation validate-template --template-body file://Bastion-Host/Bastion-Test/Private-Instance.yml; then
          echo "Error: Private Instance template validation failed. Exiting."
          aws cloudformation validate-template --template-body file://Bastion-Host/Bastion-Test/Private-Instance.yml --debug
          exit 1
        fi

        echo "Deploying Private Instance..."
        if ! aws cloudformation deploy \
          --template-file Bastion-Host/Bastion-Test/Private-Instance.yml \
          --stack-name PrivateStack \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1; then
          echo "Error: Private Instance deployment failed. Exiting."
          aws cloudformation describe-stack-events --stack-name PrivateStack --region us-east-1
          exit 1
        fi
        echo "Private Instance deployment complete."

  post_build:
    commands:
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'
