AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a Private Instance accessible only from the Tunnel Instance."

Resources:
  PrivateKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: PrivateKey
      KeyType: rsa

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH only from Tunnel Instance"
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/32"  # Will be updated dynamically in buildspec.yaml

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref PrivateKeyPair
      ImageId: ami-0020bf3f31d767322
      SubnetId: !ImportValue PrivateSubnet
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      Tags:
        - Key: Name
          Value: "PrivateInstance"

Outputs:
  PrivateInstancePrivateIP:
    Description: "Private IP of Private Instance"
    Value: !GetAtt PrivateInstance.PrivateIp
