AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a Tunnel Instance with Security Group."

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH from my IP"
      VpcId: vpc-08443a036d106568c
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 122.162.145.98/32

  TunnelInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: TunnelKey  # existing key pair
      ImageId: ami-0e2c8caa4b6378d8c
      SubnetId: subnet-039a302ff3bcd44df
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: "TunnelInstance"

Outputs:
  TunnelInstancePublicIP:
    Description: "Public IP of Tunnel Instance"
    Value: !GetAtt TunnelInstance.PublicIp
