  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Create a Tunnel Instance with Security Group."

  Resources:
    KeyPair:
      Type: AWS::EC2::KeyPair
      Properties:
        KeyName: TunnelKey
        KeyType: rsa

    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Allow SSH from my IP"
        VpcId: !ImportValue MyVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: "0.0.0.0/32"

    TunnelInstance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        KeyName: !Ref KeyPair
        ImageId: ami-004028b2e02dad333
        SubnetId: !ImportValue PublicSubnet
        SecurityGroupIds:
          - !Ref SecurityGroup
        Tags:
          - Key: Name
            Value: "TunnelInstance"

  Outputs:
    TunnelInstancePublicIP:
      Description: "Public IP of Tunnel Instance"
      Value: !GetAtt TunnelInstance.PublicIp
